substitutions:
  _PROJECT: "${_PROJECT}"
  _REGION:  "${_REGION}"
  _REPO:    "${_REPO}"
  _CLUSTER: "${_CLUSTER}"
  _CLUSTER_REGION: "${_CLUSTER_REGION}"

steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    - "build"
    - "-t"
    - "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/simple-webapp:$SHORT_SHA"
    - "."

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/simple-webapp:$SHORT_SHA"

- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      gcloud container clusters get-credentials ${_CLUSTER} \
        --region ${_CLUSTER_REGION} \
        --project ${_PROJECT}

- name: "gcr.io/cloud-builders/kubectl"
  args:
    - "apply"
    - "-f"
    - "kube-files/"
